### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by DeneshPohar** [lostromb/concentus.oggfile#19]
Unlike the https://github.com/lostromb/concentus, it's unclear to me what license this repo is under.  Can you please clarify the license, and possibly include a `LICENSE` file?

**Comment by lostromb** [comment]
![image](https://user-images.githubusercontent.com/918053/84559872-73ea8080-acf3-11ea-8fa7-5dcbeb2497cf.png)

[??????](https://github.com/lostromb/concentus/blob/master/LICENSE)

**Comment by lostromb** [comment]
Added.
