### ISSUE TITLE
Patching Concentus.Oggfile for personal use case ("premature disposal is the root of this evil")

### ISSUE THREAD

**Issue by Vivraan** [lostromb/concentus.oggfile#26]
In my codebase, I need to know my stream's `MemoryStream.Position`. Prematurely disposing of it prevents me from retrieving relevant information when uploading the bytes to Firebase Storage.

It is incredibly irritating because, without that, I can't use optimised implementations such as `Microsoft.IO.RecyclableMemoryStream`, which deviates from the `MemoryStream` API in that it prevents access to the underlying buffer even after disposal (although this is logically accurate as it uses pooled memory). At least in the case of a `MemoryStream`, the underlying buffer, if not preallocated, can be accessed after the call to `Dispose()` with the caveat that it will reallocate each time the buffer grows. Passing a size/count to the constructor just sets the length, and the position remains unretrievable regardless of implementation.

For this reason, I downloaded the source code of `Concentus.Oggfile` to my project and commented out the call to `_outputStream.Dispose()` on both the raw and the OGG write stream classes. This allows me to control the memory stream outside the wrappers.

Even from a software design standpoint, streams passed to the wrapper shouldn't be disposed of by the wrapper, even if the wrappers pretend to be streams (which they are not because they don't extend `Stream`). The wrappers technically only write headers, packets, or relevant data to a stream and are not responsible for the stream's lifecycle.

I remember vaguely that I'd come across this problem a while ago while using a variant of NAudio's logic (which, afaik, is what this one has been adapted from, too) being used for writing OGG Vorbis streams. Even then, I was just recommended to write a stream implementation, but that doesn't suffice.

**Comment by lostromb** [comment]
Right, we talked about this and the easiest solution would be to add an `ownsStream` flag to the `OggOpusWriteStream` constructor. Or I guess it could be inverted to be a `leaveOpen` flag, which seems to be a common pattern in the core runtime, for example [StreamWriter](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=net-8.0#system-io-streamwriter-ctor(system-io-stream-system-text-encoding-system-int32-system-boolean)) or [DeflateStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream.-ctor?view=net-8.0#system-io-compression-deflatestream-ctor(system-io-stream-system-io-compression-compressionmode-system-boolean)).

**Comment by Vivraan** [comment]
> Right, we talked about this and the easiest solution would be to add an `ownsStream` flag to the `OggOpusWriteStream` constructor. Or I guess it could be inverted to be a `leaveOpen` flag, which seems to be a common pattern in the core runtime, for example [StreamWriter](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=net-8.0#system-io-streamwriter-ctor(system-io-stream-system-text-encoding-system-int32-system-boolean)) or [DeflateStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream.-ctor?view=net-8.0#system-io-compression-deflatestream-ctor(system-io-stream-system-io-compression-compressionmode-system-boolean)).

Noice, that can work!

**Comment by Vivraan** [comment]
Made my own PR: https://github.com/lostromb/concentus.oggfile/pull/27

**Comment by lostromb** [comment]
This should be in package version 1.0.6 now
