### ISSUE TITLE
Failing to read number of samples in each packet (not an issue with the library)

### ISSUE THREAD

**Issue by qwbarch** [lostromb/concentus.oggfile#28]
Hello, thanks for making this library! I have an issue that's not a bug with the library itself, but was wondering if you wouldn't mind providing insight on the problem I'm facing.

I have this simple snippet that I'd expect to print out each packet's sample count:
```csharp
var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
var reader = OpusOggReadStream(decoder, fileStream);
while (reader.HasNextPacket)
{
    var packet = reader.ReadNextRawPacket();
    var packetSamples = OpusPacketInfo.GetNumSamples(packet.AsSpan(), 48000);
    Console.WriteLine(packetSamples);
}
```
The issue here is that it often prints ``-1``. Each time I run the function that executes this code, it in fact prints a different number for ``packetSamples`` each time.
Looking at the source code for ``OpusPacketInfo.GetNumSamples`` seems to be deterministic though. Do you know what might be the issue?

On the other hand, if I decode it via the read stream, it has no issues at all:
```csharp
var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
var reader = OpusOggReadStream(decoder, fileStream);
while (reader.HasNextPacket)
{
    var packet = reader.DecodeNextPacket();
    Console.WriteLine(packet.Length);
}
```

Since the first snippet fails on ``OpusPacketInfo.GetNumSamples``, I'd expect the second snippet to fail as well since it calls the same function to determine the output buffer's length.

For context, I am on netstandard2.1 due to being on unity. Is this maybe an issue that has to do with me being on netstandard2.1?

**Comment by qwbarch** [comment]
I created a ``net8.0`` app to test with, and the first snippet now runs correctly. This does seem to be an issue with me being ``.netstandard2.1``, any idea on what I can do to make this work?

**Comment by lostromb** [comment]
I don't have any definitive answers at the moment. I can say that a return value of -1 implies that the packet had a length of zero, so I don't know if that means anything. You could try logging the packet contents each time and try to find a difference.

Unity runs on Mono and I vaguely recall during my time doing C# on raspberry pi (a NetStandard library imported into NetFramework on Mono) that some compatibility aspects of it were...weird. Maybe it has something to do with the BCL library handling spans in a weird way when you call `packet.AsSpan()`.

If it is something to do with span handling you could try downgrading to `Concentus.Oggfile 1.0.4` and `Concentus 1.1.7` to see if that changes anything.... though you lose some of the potential performance that way if you also wanted to rely on the more modern `Concentus.Native` bindings.
