### ISSUE TITLE
Incompatible with concentus 1.1.4 from Nuget

### ISSUE THREAD

**Issue by mihui** [lostromb/concentus.oggfile#4]
Dear @lostromb ,

after I upgrade the `concentus` version from 1.1.3 to 1.1.4 on Nuget, there is an exception: 

`System.MissingMethodException: 'Method not found: 'Concentus.Common.SpeexResampler Concentus.Common.SpeexResampler.Create(Int32, Int32, Int32, Int32)'.'`

**Comment by lostromb** [comment]
Yes, that is an intentional regression. There was no point in having the Create() methods so instead you should just use the regular constructor. I didn't consider it happening on indirect dependencies though....sorry

**Comment by lostromb** [comment]
I will probably fix it tomorrow, just to be clear that I'm not ignoring the problem.

**Comment by mihui** [comment]
@lostromb thank you. 👍

**Comment by lostromb** [comment]
1.1.5 deployed with the change

**Comment by mihui** [comment]
@lostromb thanks, it works now.
